apiVersion: v1
kind: Secret
metadata:
  name: beer-cluster-admin-sa-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: beer-cluster-admin
type: kubernetes.io/service-account-token