/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/bwei/logging-sidecar-injector/pkg/apis/dbs/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLogInfos implements LogInfoInterface
type FakeLogInfos struct {
	Fake *FakeDbsV1alpha1
	ns   string
}

var loginfosResource = schema.GroupVersionResource{Group: "dbs.k8s.io", Version: "v1alpha1", Resource: "loginfos"}

var loginfosKind = schema.GroupVersionKind{Group: "dbs.k8s.io", Version: "v1alpha1", Kind: "LogInfo"}

// Get takes name of the logInfo, and returns the corresponding logInfo object, and an error if there is any.
func (c *FakeLogInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LogInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(loginfosResource, c.ns, name), &v1alpha1.LogInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogInfo), err
}

// List takes label and field selectors, and returns the list of LogInfos that match those selectors.
func (c *FakeLogInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LogInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(loginfosResource, loginfosKind, c.ns, opts), &v1alpha1.LogInfoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LogInfoList{ListMeta: obj.(*v1alpha1.LogInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.LogInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested logInfos.
func (c *FakeLogInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(loginfosResource, c.ns, opts))

}

// Create takes the representation of a logInfo and creates it.  Returns the server's representation of the logInfo, and an error, if there is any.
func (c *FakeLogInfos) Create(ctx context.Context, logInfo *v1alpha1.LogInfo, opts v1.CreateOptions) (result *v1alpha1.LogInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(loginfosResource, c.ns, logInfo), &v1alpha1.LogInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogInfo), err
}

// Update takes the representation of a logInfo and updates it. Returns the server's representation of the logInfo, and an error, if there is any.
func (c *FakeLogInfos) Update(ctx context.Context, logInfo *v1alpha1.LogInfo, opts v1.UpdateOptions) (result *v1alpha1.LogInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(loginfosResource, c.ns, logInfo), &v1alpha1.LogInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogInfo), err
}

// Delete takes name of the logInfo and deletes it. Returns an error if one occurs.
func (c *FakeLogInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(loginfosResource, c.ns, name, opts), &v1alpha1.LogInfo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLogInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(loginfosResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LogInfoList{})
	return err
}

// Patch applies the patch and returns the patched logInfo.
func (c *FakeLogInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LogInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(loginfosResource, c.ns, name, pt, data, subresources...), &v1alpha1.LogInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogInfo), err
}
