/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/bwei/logging-sidecar-injector/pkg/apis/dbs/v1alpha1"
	scheme "github.com/bwei/logging-sidecar-injector/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LogInfosGetter has a method to return a LogInfoInterface.
// A group's client should implement this interface.
type LogInfosGetter interface {
	LogInfos(namespace string) LogInfoInterface
}

// LogInfoInterface has methods to work with LogInfo resources.
type LogInfoInterface interface {
	Create(ctx context.Context, logInfo *v1alpha1.LogInfo, opts v1.CreateOptions) (*v1alpha1.LogInfo, error)
	Update(ctx context.Context, logInfo *v1alpha1.LogInfo, opts v1.UpdateOptions) (*v1alpha1.LogInfo, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LogInfo, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LogInfoList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LogInfo, err error)
	LogInfoExpansion
}

// logInfos implements LogInfoInterface
type logInfos struct {
	client rest.Interface
	ns     string
}

// newLogInfos returns a LogInfos
func newLogInfos(c *DbsV1alpha1Client, namespace string) *logInfos {
	return &logInfos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the logInfo, and returns the corresponding logInfo object, and an error if there is any.
func (c *logInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LogInfo, err error) {
	result = &v1alpha1.LogInfo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("loginfos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LogInfos that match those selectors.
func (c *logInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LogInfoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LogInfoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("loginfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested logInfos.
func (c *logInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("loginfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a logInfo and creates it.  Returns the server's representation of the logInfo, and an error, if there is any.
func (c *logInfos) Create(ctx context.Context, logInfo *v1alpha1.LogInfo, opts v1.CreateOptions) (result *v1alpha1.LogInfo, err error) {
	result = &v1alpha1.LogInfo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("loginfos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(logInfo).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a logInfo and updates it. Returns the server's representation of the logInfo, and an error, if there is any.
func (c *logInfos) Update(ctx context.Context, logInfo *v1alpha1.LogInfo, opts v1.UpdateOptions) (result *v1alpha1.LogInfo, err error) {
	result = &v1alpha1.LogInfo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("loginfos").
		Name(logInfo.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(logInfo).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the logInfo and deletes it. Returns an error if one occurs.
func (c *logInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("loginfos").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *logInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("loginfos").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched logInfo.
func (c *logInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LogInfo, err error) {
	result = &v1alpha1.LogInfo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("loginfos").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
